---
- hosts: all
  tasks:
    - name: Set OS distribution dependent variables
      include_vars: "{{ ansible_facts['os_family'] | lower }}.yml"
      when: ansible_facts['os_family'] == "Debian"

- hosts: all
  roles:
    - role: ome.postgresql
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]
    - role: ome.omero_server
      omero_server_selfsigned_certificates: true
      omero_server_rootpassword: ChangeMe
    - role: ome.omero_web
      omero_web_config_set:
        omero.web.application_server.host: "0.0.0.0"
  vars:
    postgresql_version: "13"
