---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: omero-all
    image: jrei/systemd-ubuntu:20.04
    command: /sbin/init
    privileged: true
    tmpfs:
      - /sys/fs/cgroup
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: test-dependencies.yml
    converge: ../../playbook.yml
scenario:
  name: ubuntu2004
verifier:
  name: testinfra
  lint:
    name: flake8
